import type { Metadata } from "next";
import { Barlow, Inter, Teachers } from "next/font/google";
import "./globals.css";

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900",],
  style: ["normal", "italic"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900",],
  style: ["normal", "italic"],
});

const teachers = Teachers({
  variable: '--font-teachers',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.variable} ${teachers.variable} ${inter.variable} font-barlow`}
      >
        {children}
      </body>
    </html>
  );
}
